<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="288" started-at="2022-01-06T09:51:38 IST" finished-at="2022-01-06T09:51:38 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="288" started-at="2022-01-06T09:51:38 IST" finished-at="2022-01-06T09:51:38 IST">
      <class name="package1.Test3Test">
        <test-method status="PASS" signature="file1()[pri:0, instance:package1.Test3Test@4d50efb8]" name="file1" duration-ms="34" started-at="2022-01-06T09:51:38 IST" finished-at="2022-01-06T09:51:38 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- file1 -->
        <test-method status="FAIL" signature="file2()[pri:0, instance:package1.Test3Test@4d50efb8]" name="file2" duration-ms="24" started-at="2022-01-06T09:51:38 IST" finished-at="2022-01-06T09:51:38 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[This is Test2]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: This is Test2
at org.testng.Assert.fail(Assert.java:97)
at package1.Test3Test.file2(Test3Test.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- file2 -->
        <test-method status="PASS" signature="file3()[pri:0, instance:package1.Test3Test@4d50efb8]" name="file3" duration-ms="13" started-at="2022-01-06T09:51:38 IST" finished-at="2022-01-06T09:51:38 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- file3 -->
      </class> <!-- package1.Test3Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
